### ISSUE TITLE
compilation fails if options are passed to \printglossary

### ISSUE THREAD

**Issue by bweigel** [cpfaff/Open-Science-Thesis#37]
hi,

I have just noticed, that passing some options to `\printglossary[options]` fails.
I have tried `\printglossary[..., listgroup]` and `\printglossary[..., nopostdot]` to override the defaults, however this gives me errors on `$ make allgloss` like this:

```
! Package xkeyval Error: `listgroup' undefined in families `printgloss'.
See the xkeyval package documentation for explanation.
```

There is a small workaround, however where you loose some flexibility. In the class file **open_science_thesis.cls** one can pass the options globally via 
`\RequirePackage[xindy, nopostdot, acronym, toc]{glossaries}`

This fix does only work for the **nopostdot** option.

I have no ideas on how to fix this using the _xkeyval_ package, since my latex skills are not very sophisticated. Help would be much appreciated.
Thanks again for this great template.

Ben

**Comment by cpfaff** [comment]
Currently investigating.

**Comment by cpfaff** [comment]
Simple I think. You use it wrong. This options you provide are not boolean flags. `listgroup` is a style and should thus specified like this: 

```
\printglossary[title=List of Terms,toctitle=Terms and abbreviations, type=\acronymtype, style=listgroup]
```

Youd need to provide the package options as key-value pairs!
